const carsConstants = {
  FETCH_CARS_STARTED: 'FETCH_CARS_STARTED',
  FETCH_CARS_SUCCESS: 'FETCH_CARS_SUCCESS',
  FETCH_CARS_ERROR: 'FETCH_CARS_ERROR',
  FETCH_CAR_STARTED: 'FETCH_CAR_STARTED',
  FETCH_CAR_SUCCESS: 'FETCH_CAR_SUCCESS',
  FETCH_CAR_ERROR: 'FETCH_CAR_ERROR',
  FETCH_COLORS: 'FETCH_COLORS',
  FETCH_MANUFACTURERS: 'FETCH_MANUFACTURERS',
  SET_PARAMS: 'SET_PARAMS'
};

export default carsConstants;
